name: Python

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13.1 (Free Threaded)
      uses: actions/setup-python@v5
      with:
        python-version: '3.13.1'
        architecture: 'x64'
        python-platform: 'win32'
        python-kind: 'freethreaded'
    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable
    - name: Install Maturin
      run: pip install maturin
    - name: Build wheel
      run: maturin build --release --bindings pyo3 --manifest-path windows-capture-python/Cargo.toml
    - name: Upload Python wheel
      uses: actions/upload-artifact@v4
      with:
        name: python-wheel
        path: target/wheels/*.whl
